/home/log/nginx/*.log {
    su www-data root
    daily
    maxsize 1G
    rotate 7
    missingok
    notifempty
    compress
    create 0644 www-data root
    sharedscripts
    postrotate
        invoke-rc.d nginx rotate >/dev/null 2>&1
    endscript
}
